title: 课程项目站点
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Giscus Comments
giscus:
  repo: Jiaju-Chen/SoftwareEngineering
  repo_id: R_kgDOP_2dlA
  category: HW1
  category_id: DIC_kwDOP_2dlM4CwnXr
  mapping: pathname
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: preferred_color_scheme
  lang: zh-CN
